### PR TITLE
upgrade all actions

### LINKED ISSUE #40: update github annotations
Node.js 16 actions are deprecated.

### PR DESCRIPTION
**Pull request by s4m5ep10l**
I've updated all actions to latest versions.

### CODE REVIEW

**Review by whyvrafvr — APPROVED** [review]
Let's test

**Comment by s4m5ep10l** [comment]
looks good 
I guess we can merge now

**Comment by s4m5ep10l** [comment]
there is an issue with codecov... what are your plans ?

**Comment by whyvrafvr** [comment]
Oh. Parallel jobs creating the same folder...

**Comment by whyvrafvr** [comment]
will handle it, don't worry ;)

**Comment by whyvrafvr** [comment]
a token is now required

**Comment by whyvrafvr** [comment]
it works buddy. I will continue to improve those parts in the workflow. Cheers

**Comment by whyvrafvr** [comment]
I've also enhanced the process for uploading the outputs of the code coverage tests (artifacts).

**Pull request merged**
